# Generated by Django 4.2.23 on 2025-10-13 20:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.time(1, 33, 40, 434969))),
                ('location', models.CharField(blank=True, choices=[('Kalyani Nagar', 'Kalyani Nagar'), ('Hinjewadi', 'Hinjewadi'), ('Shaniwar Peth', 'Shaniwar Peth'), ('Koregaon Park', 'Koregaon Park'), ('Pashan', 'Pashan'), ('Sadashiv Peth', 'Sadashiv Peth')], default='Pune', max_length=500)),
                ('volunteers_needed', models.IntegerField(blank=True, null=True)),
                ('volunteers_registered', models.IntegerField(blank=True, null=True)),
                ('cause', models.CharField(blank=True, choices=[('Education', 'Education'), ('Environment', 'Environment'), ('Health', 'Health'), ('Community Development', 'Community Development'), ('Animal Welfare', 'Animal Welfare'), ('Arts and Culture', 'Arts and Culture')], max_length=100, null=True)),
                ('skills', models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Teaching', 'Teaching'), ('Fundraising', 'Fundraising'), ('Event Planning', 'Event Planning'), ('Social Media', 'Social Media'), ('Photography', 'Photography'), ('Public Speaking', 'Public Speaking')], max_length=100, null=True)),
                ('impact', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Registered', 'Registered'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='userfuncs.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
