# Generated by Django 4.2.23 on 2025-10-14 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0003_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(22, 0, 46, 437298)),
        ),
    ]
