# Generated by Django 4.2.23 on 2025-10-21 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0004_alter_events_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cause',
        ),
        migrations.AddField(
            model_name='events',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='causes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='events',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(1, 39, 39, 607619)),
        ),
    ]
