# Generated by Django 4.2.23 on 2025-10-21 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0005_remove_events_cause_events_address_events_causes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(1, 50, 4, 233396)),
        ),
    ]
