# Generated by Django 4.2.23 on 2025-10-21 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0006_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(1, 50, 18, 296774)),
        ),
    ]
