# Generated by Django 4.2.23 on 2025-10-28 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0007_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(9, 54, 16, 900900)),
        ),
    ]
