# Generated by Django 4.2.23 on 2025-10-30 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0009_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(0, 58, 37, 908757)),
        ),
    ]
