# Generated by Django 4.2.23 on 2025-10-31 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0010_alter_events_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.time(12, 8, 8, 689835)),
        ),
    ]
