# Generated by Django 4.2.23 on 2025-12-17 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0011_alter_events_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AddField(
            model_name='events',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='events',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
