# Generated by Django 4.2.23 on 2025-12-17 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userfuncs', '0012_remove_events_date_remove_events_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
