# Generated by Django 4.2.23 on 2025-10-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hoursvolunteered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
