# Generated by Django 4.2.23 on 2025-10-12 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studentid', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
