# Generated by Django 4.2.23 on 2025-10-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='studentid',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
